/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"fronius-wattpilot adapter settings": {
		"en": "Adapter settings for fronius-wattpilot",
		"de": "Adaptereinstellungen für fronius-wattpilot",
		"ru": "Настройки адаптера для fronius-wattpilot",
		"pt": "Configurações do adaptador para fronius-wattpilot",
		"nl": "Adapterinstellingen voor fronius-wattpilot",
		"fr": "Paramètres d'adaptateur pour fronius-wattpilot",
		"it": "Impostazioni dell'adattatore per fronius-wattpilot",
		"es": "Ajustes del adaptador para fronius-wattpilot",
		"pl": "Ustawienia adaptera dla fronius-wattpilot",
		"zh-cn": "fronius-wattpilot的适配器设置"
	},
	"IP-Address (If you use Cloud leave blank)": {
		"en": "IP-Address (If you use Cloud leave blank)",
		"de": "IP-Adresse (Bei Verwendung der Cloud, hier nichts eintragen)",
		"ru": "IP-адрес (Если вы используете облако оставить пустым)",
		"pt": "Endereço IP (Se você usar Nuvem deixa em branco)",
		"nl": "IP-Addres Als je Cloud gebruikt, laat dan los",
		"fr": "IP-Address (Si vous utilisez Cloud leave blank)",
		"it": "Indirizzo IP (Se si utilizza Cloud lasciare vuoto)",
		"es": "IP-Address (Si usas Cloud Leave blank)",
		"pl": "IP-Address (Jeśli używamy pustego rzutu)",
		"zh-cn": "IP-Address (请你使用Cloud 空白)"
	},
	"Not recommended in a local environment": {
		"en": "Not recommended in a local environment",
		"de": "Nicht empfohlen in einer lokalen Umgebung",
		"ru": "Не рекомендуется в локальной среде",
		"pt": "Não recomendado em um ambiente local",
		"nl": "Niet aanbevolen in een lokale omgeving",
		"fr": "Non recommandé dans un environnement local",
		"it": "Non raccomandato in un ambiente locale",
		"es": "No recomendado en un entorno local",
		"pl": "Nie rekomendowany w środowisku lokalnym",
		"zh-cn": "地方环境建议"
	},
	"Only read most common data-points": {
		"en": "Only read most common data-points",
		"de": "Nur die gängigsten Datenpunkte lesen",
		"ru": "Только читайте наиболее распространенные данные",
		"pt": "Apenas leia os datapoints mais comuns",
		"nl": "Lees alleen de meeste gemeenschappelijke datapoints",
		"fr": "Seulement lire les points de données les plus courants",
		"it": "Leggere solo i punti di dati più comuni",
		"es": "Sólo leen los puntos de datos más comunes",
		"pl": "Przeczytany jedynie na podstawie danych",
		"zh-cn": "只有阅读最常见的数据点"
	},
	"Password": {
		"en": "Password",
		"de": "Passwort",
		"ru": "Пароль",
		"pt": "Senha",
		"nl": "Wachtwoord",
		"fr": "Mot de passe",
		"it": "Password",
		"es": "Contraseña",
		"pl": "Password",
		"zh-cn": "护照"
	},
	"Serial Number (Only in Cloud mode)": {
		"en": "Serial Number (Only in Cloud mode)",
		"de": "Seriennummer (nur im Cloud-Modus)",
		"ru": "Серийный номер (только в облачном режиме)",
		"pt": "Número de série (apenas no modo Cloud)",
		"nl": "Serienummer (Only in Cloud mode)",
		"fr": "Numéro de série (uniquement en mode Cloud)",
		"it": "Numero seriale (solo in modalità Cloud)",
		"es": "Número de serie (sólo en modo Cloud)",
		"pl": "Serial Number (ang.)",
		"zh-cn": "数量(在Cloud模式)"
	},
	"Uncheck to get any data available from API": {
		"en": "Uncheck to get any data available from API",
		"de": "Deaktivieren um alle verfügbaren Daten der API auszulesen",
		"ru": "Не проверять, чтобы получить какие-либо данные, доступные из API",
		"pt": "Desmarque para obter quaisquer dados disponíveis a partir da API",
		"nl": "Oncontroleer alle gegevens van API",
		"fr": "Décochez pour obtenir toutes les données disponibles de l'API",
		"it": "Deselezionare per ottenere qualsiasi dato disponibile da API",
		"es": "Desmarque para obtener los datos disponibles en la API",
		"pl": "Nie sprawdzaj czy dane dostępne są z API",
		"zh-cn": "核对获得非专利计划提供的任何数据"
	},
	"Use cloud to get data from the Pilot": {
		"en": "Use cloud to get data from the Pilot",
		"de": "Cloud verwenden, um Daten vom Pilot zu erhalten",
		"ru": "Используйте облако, чтобы получить данные с пилота",
		"pt": "Use nuvem para obter dados do piloto",
		"nl": "Gebruik wolk om Data van de Pilot te halen",
		"fr": "Utilisez le nuage pour obtenir des données du pilote",
		"it": "Usa cloud per ottenere i dati dal pilota",
		"es": "Utilice la nube para obtener datos del Piloto",
		"pl": "Użycie chmur dostarczenia danych z pilota",
		"zh-cn": "利用云雾器从试验中获得数据"
	},
	"only needed if Only read most... is checked": {
		"en": "only needed if \"Only read most...\" is checked",
		"de": "nur benötigt, wenn \"nur am meisten lesen\". wird geprüft",
		"ru": "только нужно, если \"Только прочитайте больше\". проверяется",
		"pt": "só precisava se \"Somente ler mais\". é verificado",
		"nl": "alleen nodig als \"lezen het meest\". wordt gecontroleerd",
		"fr": "seulement nécessaire si \"Only read most\". est vérifiée",
		"it": "solo bisogno se \"Solo leggere la maggior parte\". è controllato",
		"es": "sólo se necesita si \"sólo leer la mayoría\". Se ha comprobado",
		"pl": "zdecydowano tylko wtedy, gdy „Only read most”. sprawdzić",
		"uk": "тільки потрібно, якщо \"Тільки прочитати більшість\". перевіряється",
		"zh-cn": "只需要“最阅读”。 检查"
	},
	"Use bcrypt for authentication (instead of PBKDF2)": {
		"en": "Use bcrypt for authentication (instead of PBKDF2)",
		"de": "Bcrypt für die Authentifizierung verwenden (statt PBKDF2)",
		"ru": "Использовать bcrypt для аутентификации (вместо PBKDF2)",
		"pt": "Use bcrypt para autenticação (em vez de PBKDF2)",
		"nl": "Gebruik bcrypt voor authenticatie (in plaats van PBKDF2)",
		"fr": "Utiliser bcrypt pour l'authentification (au lieu de PBKDF2)",
		"it": "Usa bcrypt per l'autenticazione (invece di PBKDF2)",
		"es": "Usar bcrypt para autenticación (en lugar de PBKDF2)",
		"pl": "Użyj bcrypt do uwierzytelniania (zamiast PBKDF2)",
		"zh-cn": "使用 bcrypt 进行身份验证(代替 PBKDF2)"
	},
	"Enable only if your device/firmware requires bcrypt": {
		"en": "Enable only if your device/firmware requires bcrypt",
		"de": "Nur aktivieren, wenn Ihr Gerät/Firmware bcrypt benötigt",
		"ru": "Включайте только если ваше устройство/прошивка требует bcrypt",
		"pt": "Ativar apenas se seu dispositivo/firmware exigir bcrypt",
		"nl": "Alleen inschakelen als uw apparaat/firmware bcrypt vereist",
		"fr": "Activer uniquement si votre appareil/firmware nécessite bcrypt",
		"it": "Abilita solo se il tuo dispositivo/firmware richiede bcrypt",
		"es": "Habilitar solo si su dispositivo/firmware requiere bcrypt",
		"pl": "Włącz tylko, jeśli urządzenie/firmware wymaga bcrypt",
		"zh-cn": "仅在设备/固件需要 bcrypt 时启用"
	},
	"Interval to receive Wattpilot data (s)": {
		"en": "Interval to receive Wattpilot data (s)",
		"de": "Intervall zum Empfang von Wattpilot-Daten (s)",
		"ru": "Интервал получения данных Wattpilot (с)",
		"pt": "Intervalo para receber dados do Wattpilot (s)",
		"nl": "Interval om Wattpilot-gegevens te ontvangen (s)",
		"fr": "Intervalle pour recevoir les données Wattpilot (s)",
		"it": "Intervallo per ricevere i dati Wattpilot (s)",
		"es": "Intervalo para recibir datos de Wattpilot (s)",
		"pl": "Interwał odbierania danych Wattpilot (s)",
		"uk": "Інтервал отримання даних Wattpilot (с)",
		"zh-cn": "接收 Wattpilot 数据的时间间隔 (s)"
	},
	"Only Common Data": {
		"en": "Only Common Data",
		"de": "Nur gängige Daten",
		"ru": "Только общие данные",
		"pt": "Apenas dados comuns",
		"nl": "Alleen algemene gegevens",
		"fr": "Uniquement les données communes",
		"it": "Solo dati comuni",
		"es": "Sólo datos comunes",
		"pl": "Tylko wspólne dane",
		"uk": "Тільки загальні дані",
		"zh-cn": "仅通用数据"
	},
	"Give additional Parameters as semicolon (;) seperated list": {
		"en": "Give additional Parameters as semicolon (;) seperated list",
		"de": "Zusätzliche Parameter als Semikolon (;) getrennte Liste angeben",
		"ru": "Укажите дополнительные параметры в виде списка, разделенного точкой с запятой (;)",
		"pt": "Forneça parâmetros adicionais como uma lista separada por ponto e vírgula (;)",
		"nl": "Geef aanvullende parameters op als een door puntkomma's (;) gescheiden lijst",
		"fr": "Donnez des paramètres supplémentaires sous forme de liste séparée par des points-virgules (;)",
		"it": "Fornire parametri aggiuntivi come elenco separato da punti e virgola (;)",
		"es": "Proporcione parámetros adicionales como una lista separada por punto y coma (;)",
		"pl": "Podaj dodatkowe parametry jako listę oddzieloną średnikami (;)",
		"uk": "Надайте додаткові параметри у вигляді списку, розділеного крапкою з комою (;)",
		"zh-cn": "以分号 (;) 分割的列表形式给出附加参数"
	}
};